# pandas

In [1]:
# import the required packages

import numpy as np
import pandas as pd

In [2]:
# prerequisities

import warnings
warnings.filterwarnings(action="ignore")

In [3]:
a1=[10,20,30,40,50]
print(f"A1 ={a1}   Type={type(a1)}")

A1 =[10, 20, 30, 40, 50]   Type=<class 'list'>

In [4]:
n_array=np.array([10,20,30,40,50])
print(f"N_ARR ={n_array}   Type={type(n_array)}")

N_ARR =[10 20 30 40 50]   Type=<class 'numpy.ndarray'>

In [5]:
def function1():
    n_series=pd.Series([10,20,30,40,50,60])
    print(f"Type={type(n_series)}")
    print(f"DType={n_series.dtype}")
    print(f"Size={n_series.size}")
    print(f"DIM={n_series.ndim}")
    print(f"N_Bytes={n_series.nbytes}")

function1()

Type=<class 'pandas.core.series.Series'>
DType=int64
Size=6
DIM=1
N_Bytes=48

In [6]:
n_series=pd.Series([10,20,30,40,50])
print(f"Keys ={n_series.keys()}")
print(f"Value={n_series.values}")

Keys =RangeIndex(start=0, stop=5, step=1)
Value=[10 20 30 40 50]

# Indexing

In [8]:
s1=pd.Series([10,20,30,40,50,60])
print(s1)
print(f"S1[2]={s1[2]}")

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64
S1[2]=30

# Create pandas using dictionary

In [9]:
s1=pd.Series({"Name":"sakshi","org":"Sunbeam","id":123,"course":"python"})
print(s1)
print(f"s1[Name] = {s1['Name']}")
print(f"s1[0] = {s1[0]}")

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Name       sakshi
org       Sunbeam
id            123
course     python
dtype: object
s1[Name] = sakshi
s1[0] = sakshi

In [10]:
students=pd.Series(["s1","s2","s3","s4"])
marks=pd.Series([25,30,35,40])
print(students)
print(marks)

0    s1
1    s2
2    s3
3    s4
dtype: object
0    25
1    30
2    35
3    40
dtype: int64

In [11]:
students=pd.Series(["s1","s2","s3","s4"])
marks=pd.Series([25,30,35,40],index=students)
print(marks)

s1    25
s2    30
s3    35
s4    40
dtype: int64

In [12]:
marks=pd.Series([25,30,35,40])
students=pd.Series(["s1","s2","s3","s4"],index=marks)
print(students)

25    s1
30    s2
35    s3
40    s4
dtype: object

# Create Dataframe using Dictiionary

In [18]:
data={'Name':['n1','n2','n3','n4'],'Age':[20,25,30,35]}
df=pd.DataFrame(data,index=['rank1','rank2','rank3','rank4'])
print(df)

      Name  Age
rank1   n1   20
rank2   n2   25
rank3   n3   30
rank4   n4   35

In [19]:
def function2():
    p1=({'name':'p1','age':25,'id':1234})
    p2=({'name':'p2','age':35,'id':5678})
    p3=({'name':'p3','age':30,'id':3456})
    p4=({'name':'p4','age':40,'id':6789})

    s1=pd.Series(p1)
    s2=pd.Series(p2)
    s3=pd.Series(p3)
    s4=pd.Series(p4)

    df=pd.DataFrame([s1,s2,s3,s4])
    print(s1)
    print(s2)
    print(s3)
    print(s4)
    
    print(df)
function2()

name      p1
age       25
id      1234
dtype: object
name      p2
age       35
id      5678
dtype: object
name      p3
age       30
id      3456
dtype: object
name      p4
age       40
id      6789
dtype: object
  name  age    id
0   p1   25  1234
1   p2   35  5678
2   p3   30  3456
3   p4   40  6789

In [20]:
def function3():
    p1=({'name':'p1','age':25,'id':1234})
    p2=({'name':'p2','age':35,'id':5678})
    p3=({'name':'p3','age':30,'id':3456})
    p4=({'name':'p4','age':40,'marks':35})

    s1=pd.Series(p1)
    s2=pd.Series(p2)
    s3=pd.Series(p3)
    s4=pd.Series(p4)

    df=pd.DataFrame([s1,s2,s3,s4])
    print(df)
function3()

  name  age      id  marks
0   p1   25  1234.0    NaN
1   p2   35  5678.0    NaN
2   p3   30  3456.0    NaN
3   p4   40     NaN   35.0

In [21]:
def function4():
    # filtering
    salaries=pd.Series([30,35,45,40,70,90,80,75])
    # find salaries above 70k
    print(f"Salaries above 70k = \n{salaries[salaries>70]}")
function4()

Salaries above 70k =
5    90
6    80
7    75
dtype: int64

In [22]:
# load the datset
df=pd.read_csv("Salary_Data.csv")
print(df)

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.0  140000
31             12.0  155000
32             13.0  156000

# EDA

In [23]:
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [24]:
df.head(10)

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
5              2.9   56642
6              3.0   60150
7              3.2   54445
8              3.2   64445
9              3.7   57189

In [25]:
df.tail(7)

    YearsExperience  Salary
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.0  140000
31             12.0  155000
32             13.0  156000

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  33 non-null     float64
 1   Salary           33 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 656.0 bytes

In [27]:
df.describe()

       YearsExperience         Salary
count        33.000000      33.000000
mean          5.921212   82760.303030
std           3.342413   34014.620992
min           1.100000   37731.000000
25%           3.200000   56957.000000
50%           5.100000   67938.000000
75%           8.700000  109431.000000
max          13.000000  156000.000000